language: java

jdk:
  - oraclejdk8
  - oraclejdk9

matrix:
  allow_failures:
    - jdk: oraclejdk9

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java9-installer
cache:
  directories:
    - $HOME/.m2
before_script: java -version
script: ./mvnw install
